-- Run this script while connected to the Oracle schema used by the API.
-- Oracle does not use CREATE DATABASE or USE statements.

BEGIN EXECUTE IMMEDIATE 'DROP TABLE report_history CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE scenario_results CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE risk_metrics CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE scenarios CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE market_rates CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE cash_flows CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE liabilities CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE assets CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'ANALYST' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assets (
    asset_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name VARCHAR2(100) NOT NULL,
    asset_type VARCHAR2(50) NOT NULL,
    principal_amount NUMBER(20,2) NOT NULL,
    interest_rate NUMBER(7,4) NOT NULL,
    rate_type VARCHAR2(20) NOT NULL,
    maturity_date DATE,
    currency VARCHAR2(10) DEFAULT 'INR',
    duration NUMBER(10,4),
    is_rate_sensitive NUMBER(1) DEFAULT 0,
    is_liquid NUMBER(1) DEFAULT 0,
    credit_status VARCHAR2(20) DEFAULT 'STANDARD',
    asset_status VARCHAR2(20) DEFAULT 'ACTIVE'
);

CREATE TABLE liabilities (
    liability_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    liability_name VARCHAR2(100) NOT NULL,
    liability_type VARCHAR2(50) NOT NULL,
    principal_amount NUMBER(20,2) NOT NULL,
    interest_rate NUMBER(7,4) NOT NULL,
    rate_type VARCHAR2(20) NOT NULL,
    maturity_date DATE,
    currency VARCHAR2(10) DEFAULT 'INR',
    duration NUMBER(10,4),
    is_rate_sensitive NUMBER(1) DEFAULT 0,
    is_short_term NUMBER(1) DEFAULT 0,
    liability_status VARCHAR2(20) DEFAULT 'ACTIVE'
);

CREATE TABLE cash_flows (
    flow_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id NUMBER,
    liability_id NUMBER,
    flow_date DATE NOT NULL,
    amount NUMBER(20,2) NOT NULL,
    flow_type VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_cashflow_asset FOREIGN KEY (asset_id) REFERENCES assets(asset_id) ON DELETE SET NULL,
    CONSTRAINT fk_cashflow_liability FOREIGN KEY (liability_id) REFERENCES liabilities(liability_id) ON DELETE SET NULL
);

CREATE TABLE market_rates (
    rate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_date DATE NOT NULL,
    rate_type VARCHAR2(50) NOT NULL,
    tenor_months NUMBER(10) NOT NULL,
    interest_rate NUMBER(7,4) NOT NULL,
    currency VARCHAR2(10) DEFAULT 'INR'
);

CREATE TABLE scenarios (
    scenario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_name VARCHAR2(100) NOT NULL,
    interest_rate_shift_bp NUMBER(10) DEFAULT 0,
    liquidity_shock_pct NUMBER(7,4) DEFAULT 0.0000,
    credit_shock_pct NUMBER(7,4) DEFAULT 0.0000,
    scenario_date DATE NOT NULL,
    description VARCHAR2(255)
);

CREATE TABLE risk_metrics (
    metric_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id NUMBER,
    reporting_date DATE NOT NULL,
    total_assets NUMBER(20,2) DEFAULT 0.00,
    total_liabilities NUMBER(20,2) DEFAULT 0.00,
    net_interest_income NUMBER(20,2) DEFAULT 0.00,
    liquidity_ratio NUMBER(10,4) DEFAULT 0.0000,
    duration_gap NUMBER(10,4) DEFAULT 0.0000,
    credit_risk_score NUMBER(10,4) DEFAULT 0.0000,
    CONSTRAINT fk_risk_metric_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios(scenario_id) ON DELETE SET NULL
);

CREATE TABLE scenario_results (
    result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id NUMBER NOT NULL,
    metric_name VARCHAR2(100) NOT NULL,
    baseline_value NUMBER(20,2) DEFAULT 0.00,
    scenario_value NUMBER(20,2) DEFAULT 0.00,
    impact_value NUMBER(20,2) DEFAULT 0.00,
    CONSTRAINT fk_scenario_result_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios(scenario_id) ON DELETE CASCADE
);

CREATE TABLE report_history (
    report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_name VARCHAR2(100) NOT NULL,
    report_type VARCHAR2(50) NOT NULL,
    generated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    generated_by NUMBER,
    summary VARCHAR2(255),
    CONSTRAINT fk_report_user FOREIGN KEY (generated_by) REFERENCES users(user_id) ON DELETE SET NULL
);
